import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ReactECharts from "echarts-for-react";
import { useLayoutEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

var ROOT_PATH = "https://echarts.apache.org/examples";

export default function Home() {
  useLayoutEffect(() => {
    if (typeof window !== "undefined") {
      require("echarts-gl");
      // use echarts here
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ReactECharts
          style={{ width: "80%", height: "500px" }}
          option={{
            backgroundColor: "#000",
            globe: {
              baseTexture: "/images/earth.jpg",
              heightTexture: "/images/bathymetry_bw_composite_4k.jpg",
              displacementScale: 0.1,
              shading: "lambert",
              environment: "/images/starfield.jpg",
              light: {
                ambient: {
                  intensity: 0.1,
                },
                main: {
                  intensity: 1.5,
                },
              },
              layers: [
                {
                  type: "blend",
                  blendTo: "emission",
                  texture: "/images/night.jpg",
                },
                {
                  type: "overlay",
                  texture: "/images/clouds.png",
                  shading: "lambert",
                  distance: 5,
                },
              ],
            },
            series: [],
          }}
        />
      </main>
    </>
  );
}
